name: Tự động Build và Deploy lên cPanel

on:
  push:
    branches:
      - main

jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Lấy source code mới nhất
      uses: actions/checkout@v3

    - name: Cài đặt Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    # Chỉ định chạy npm install bên trong thư mục frontend
    - name: Cài đặt thư viện (Dependencies)
      working-directory: ./frontend
      run: npm install

    # Chỉ định build Vite bên trong thư mục frontend
    - name: Build Project bằng Vite
      working-directory: ./frontend
      run: npm run build

    # Đồng bộ thư mục frontend/dist lên cPanel thông qua FTP
    - name: Đồng bộ file lên cPanel
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./frontend/dist/
        server-dir: /public_html/
        
        # Cấu hình tối ưu để tránh lỗi Timeout
        protocol: ftp
        port: 21
        port-strict: false
        passive: true