name: Tự động Build và Deploy lên cPanel

on:
  push:
    branches:
      - main  # Thay bằng 'master' nếu repo của bạn dùng nhánh master

jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Lấy source code mới nhất
      uses: actions/checkout@v3

    - name: Cài đặt Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Cài đặt thư viện (Dependencies)
      run: npm install

    - name: Build Project bằng Vite
      run: npm run build

    - name: Đồng bộ file lên cPanel
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./dist/
        server-dir: /public_html/
        protocol: ftp
        port: 21